import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Appshell from "@/component/Appshell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portofolio Athela09",
  description: "Generated by create next app",
  icons: {
    icon: "/nft/kensa #4.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Appshell>{children}</Appshell>
      </body>
    </html>
  );
}
